format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "One"
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
